CREATE TABLE "rides" (
	"id" serial PRIMARY KEY NOT NULL,
	"passenger_id" integer NOT NULL,
	"driver_id" integer,
	"assigned_driver_id" integer,
	"vehicle_type" text NOT NULL,
	"pickup_lat" numeric NOT NULL,
	"pickup_lng" numeric NOT NULL,
	"drop_lat" numeric NOT NULL,
	"drop_lng" numeric NOT NULL,
	"distance_km" numeric(10, 2) NOT NULL,
	"fare" numeric(10, 2) NOT NULL,
	"commission" numeric(10, 2) NOT NULL,
	"driver_earning" numeric(10, 2) NOT NULL,
	"status" varchar(30) DEFAULT 'requested',
	"otp" varchar(10),
	"payment_method" text DEFAULT 'cash',
	"customer_paid" boolean DEFAULT false,
	"driver_confirmed" boolean DEFAULT false,
	"driver_queue" text,
	"queue_index" integer DEFAULT 0,
	"rejected_drivers" text,
	"created_at" timestamp DEFAULT now(),
	"pickup_address" text,
	"drop_address" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"firebase_uid" text NOT NULL,
	"name" text NOT NULL,
	"phone" text NOT NULL,
	"role" text DEFAULT 'passenger' NOT NULL,
	"vehicle_type" text,
	"vehicle_number" text,
	"is_online" boolean DEFAULT false,
	"push_token" text,
	"current_lat" numeric,
	"current_lng" numeric,
	"upi_id" text,
	"upi_name" text,
	"total_earnings" numeric DEFAULT '0',
	"wallet_balance" numeric DEFAULT '0',
	"wallet_paid" numeric DEFAULT '0',
	"created_at" timestamp DEFAULT now(),
	"license_url" text,
	"vehicle_image_url" text,
	"profile_image_url" text,
	"is_approved" boolean DEFAULT false,
	CONSTRAINT "users_firebase_uid_unique" UNIQUE("firebase_uid")
);
